### ISSUE TITLE
MVP Review

### ISSUE THREAD

**Issue by danemauland** [Lijun-Gan/Amazen#1]
Hey Lijun! Great work on your MVP list. It's clear you thought through the project and you've figured out which direction to go. I just have some minor points to consider:

Product Search
-Order you MVP in the order of their completion dates
-What is the search text matched against? The book title? Any word in the whole book? Customer reviews?

Books recommendation
-This is very ambitious, even if it was a bonus feature. If you want recommendations, consider just seeding some recommendations. Coming up with recommended books based on browser history would likely take weeks to implement, and your time would be better spent on other things.
Wishlist
-Move this to being a bonus feature. This will be a great feature, but you'll have plenty of other stuff to focus on the next two weeks.

**Comment by Lijun-Gan** [comment]
Thank you!!!
