### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by danemauland** [Lijun-Gan/Amazen#2]
Great work on your schema as well! It's well thought-out and hits all the major points. A few suggestions:

'-List associations/what each foreign key references below each table
-remove Format table
-make clear that WishLists will be a bonus feature
Books
-Store the price as cents, so you can store it as an integer (e.g. the price for a book that costs $9.99 would be stored as 999)
Pictures
-image_url should have a not null constraint, since If image_url is blank, that entry is useless

**Comment by Lijun-Gan** [comment]
Thank you !!!
