### ISSUE TITLE
Backend Routes Review

### ISSUE THREAD

**Issue by danemauland** [Lijun-Gan/Amazen#4]
Your backend routes page is a good base! Here are some things to consider:

User
-What's the route for a user signing up?
-Why do you need to get all of a user's reviews? I don't see an MVP that needs that information.

Book
-If you're allowing users to search for books, you're going to need a backend route to process that search

Review
-POST - a review "belongs to" a book, right? How could you change the URI to include information about which book the review is for?

Cart
-While you definitely want a way to remove a single book from a cart, you probably want a way to delete all books from the cart (if a user checks out, you need to empty out their cart, right?) and the way you currently have it written, most people would assume the :id in your DELETE would refer to a cart id. So, what route should you use to delete/empty a whole cart, and what route should you use to remove a specific book from a cart?

**Comment by Lijun-Gan** [comment]
Thank you !!!
