### ISSUE TITLE
Frontend Routes Review

### ISSUE THREAD

**Issue by danemauland** [Lijun-Gan/Amazen#5]
Hi Lijun, your frontend routes page is a good start, but I think the below points could use some more thought:

/users/:userId
-I'm not seeing anything in your MVPs about a user show page. Let's leave this off for now, but you can feel free to add it in later as a bonus feature.
/users/:userId/cart
-Users can only ever see their own cart, right? If so, is there a more basic route you can use?
/reviews/:id/edit
-Does Amazon bring you to a new page in order to edit your reviews? If so, disregard this. If not, wouldn't you just edit the review directly on the book show page?
/reviews/:id/new
-Same as above, do you need a new page to leave a review or is it done on the same page as the book show?
/review/:id/edit
-Is this a duplicate of the above edit?
/wishlists/:id
-Make clear this is a bonus

**Comment by Lijun-Gan** [comment]
Thank you !!!
