### ISSUE TITLE
Design Doc Review #2

### ISSUE THREAD

**Issue by danemauland** [Lijun-Gan/Amazen#6]
Nice work with the revisions! Here are a few more things I spotted:

## MVPs
Product Search
-I'd recommend just searching based on the book title if you allow users to filter by category

## Schema
Prices
-note that price is stored in cents

Books
-Anything that can be used to search/filter books should be indexed to allow for faster lookup times

Prices
-add a constraint to make sure the combination of book_id and book_format is unique
-add an inclusion validation for book_format

CartItems
-remove cart_id
-add a uniqueness constraint on the combination of user_id and book_id

## Sample State
books
'-Change the "price" key in books to priceIDs (or something similar)
users
-Think about what information you really need here. Are you ever going to be displaying other users' email addresses? If not, it probably doesn't make sense to send that information to the frontend.
cartItems
-Remove cart_id

## Backend Routes
Review
-remove the /edit from PATCH /api/reviews/:id/edit

Cart
-If a user wants to purchase two of the same books, how is the quantity updated?

**Comment by Lijun-Gan** [comment]
Thank you for the feedback !!!!!

Sample State - users
-Think about what information you really need here. Are you ever going to be displaying other users' email addresses? If not, it probably doesn't make sense to send that information to the frontend

---- I need a user email and phone number for my auth part. the email /phone number is on the second sign-in page. I'm not sure if I need them in the sample state?

Backend Routes - Cart
-If a user wants to purchase two of the same books, how is the quantity updated?

---- I guess it's going to be PATCH /api/cart/edit  ???

**Comment by danemauland** [comment]
Schema
Add index on book title

Sample State - users
Exactly, you don't need the email address/phone number in the state. Outside of signing in, keep those in the backend. 

Backend Routes - Cart
Exactly, add that route in

**Comment by Lijun-Gan** [comment]
Got it. Thank you!!!
