### ISSUE TITLE
second review request

### ISSUE THREAD

**Issue by Lijun-Gan** [Lijun-Gan/Amazen#8]
- home page 
- individual book page
- customer reviews

Thank you !

**Comment by danemauland** [comment]
Nice job! See below for comments.

# Home Page
Don't use screenshots as discussed
"Shop by Category" text should be black
"Books at Amazen" text should be black
Style books to be smaller to match Amazon. You can add more seeds later to fill the page. That also includes:
 - Style the book names as links
 -  Remove the space between the $ and the number for the price
 - Less space between the review number and the stars
 - Make the stars bigger (if you can)
 
# Individual book page
Make the changes we discussed, including:
 - setting min/max width for the main page content
 - Moving the "About the Book" and/or "About the Author" sections to between the book and the sidebar

Other changes:
 - have a default book format selected (can just be the first one) so the sidebar price is pre-loaded and not at 0.00
 - Remove the space in the sidebar between "format" and the colon
 - The styling for your "Add to Cart" button should be applied to the button itself, not the div wrapping it

# Reviews
## Sidebar
Make the stars bigger (if possible)
The text telling the number of stars (for example, "4.50 out of 5") should be black and larger
The "global ratings" text should be gray, not black
Add hover effects to "write a customer review" button
## review items
- "reviewed in the United States..." text should be gray
- Text in the body of the review should be darker. This might just need a heavier font weight, it's hard to tell at a glance

## Creating a review
- Clicking 4 stars shows my review as 5 stars on the product show page, and leaving a review of 3 stars shows as 3.5 stars
- set a max width on the content here too
- Missing a question mark on the end of the headline placeholder text
- Review borders--they are too dark/sharp
- Typo on the error message for not submitting a body for the review

**Comment by Lijun-Gan** [comment]
Thank you!
The styling for your "Add to Cart" button should be applied to the button itself, not the div wrapping it ----this doesnot work, not sure why 

Clicking 4 stars shows my review as 5 stars on the product show page, and leaving a review of 3 stars shows as 3.5 stars -- my pages looks ok. 


Done!!!!
